### ISSUE TITLE
consolidate and share test fixtures with mapbox-gl-native

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-lint#29]
mapbox-gl-native has some style parsing test fixtures [here](https://github.com/mapbox/mapbox-gl-native/tree/master/test/fixtures/style_parser). We should eliminate any overlap and share the same fixtures between mapbox-gl-style-lint and the native style parser. Probably moving them to mapbox-gl-test-suite.

/cc @mikemorris

**Comment by tmcw** [comment]
https://github.com/mapbox/mapbox-gl-style-spec/issues/262
