### ISSUE TITLE
Warn about duplicate layers that are not refs

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-style-lint#36]
Not using a ref when you have a layer with the same layer/source-layer/type makes this layer's parse unnecessarily 2 times slower. We need to warn about all such occasions so that our styles are always as fast possible. cc @lbud

**Comment by tmcw** [comment]
This will likely require a major version bump, since the current API returns `[Error, Error.. ]` from validate. That said :+1: for biting this off and expanding the scope into warnings like this one.

**Comment by mourner** [comment]
Or we could throw an error on this for now since it's pretty much always undesired behavior.

**Comment by tmcw** [comment]
Let's not do that until GL Online never creates this kind of layer.

Also: isn't the initial description a little inaccurate - it's not just layer/source-layer/type, but also all layout properties. That additional restriction makes this a much narrower corner case.

**Comment by jfirebaugh** [comment]
⇢ https://github.com/mapbox/mapbox-gl-style-spec/issues/265
