### ISSUE TITLE
Ignore styles API metadata props

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-lint#39]
add to list of known props:

![screen shot 2015-01-26 at 3 46 21 pm](https://cloud.githubusercontent.com/assets/4551508/5910903/2a31c85e-a574-11e4-8bbb-23171495c4a8.png)

**Comment by jfirebaugh** [comment]
@peterqliu AFAICT these are already tolerated. See commit ^ and #34.

Can you reproduce your screenshot?

**Comment by peterqliu** [comment]
@jfirebaugh I can. But do I need to fetch the latest of anything?

![screen shot 2015-02-16 at 12 22 05 pm](https://cloud.githubusercontent.com/assets/4551508/6218753/72ea0e68-b5d6-11e4-84a2-407ea536425a.png)

**Comment by jfirebaugh** [comment]
Yeah, you need the latest version of `mapbox-gl-style-lint`. The version you have is still on v6.
