### ISSUE TITLE
provide an interface to validate that pulls in only latest style spec reference

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-lint#50]
Followup to #48.

Currently validate supports validation of any style version, and thus has to pull in the style reference for all of them. But for gl-js we want to avoid depending on any style spec json other than the current version. That's the reason for https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/reference.js

Not sure how to resolve this.

**Comment by tristen** [comment]
Does the validator need to support previous versions? It would be great to just `require('mapbox-gl-style-spec/reference/_latest_') while legacy must migrate.

**Comment by tristen** [comment]
Another idea might be to cat the spec version require and validation script into separate scripts for each i.e. `validate/v7/parsed.js`:

``` js
var spec = require('mapbox-gl-style-spec/reference/v7');

// validation ...
```

This seems less ideal though.

**Comment by jfirebaugh** [comment]
> Does the validator need to support previous versions?

Yes, for style API reasons, see #44.

I think I figured out a solution with cooperation from mapbox-gl-style-spec, see above commits.
