### ISSUE TITLE
handle transition properties

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-lint#51]
The validator should handle `*-transition` properties for all properties in the style spec with `"transition": true`.

The type to validate these values against is [here](https://github.com/mapbox/mapbox-gl-style-spec/blob/82e0394f25ecf2ed90e3d243d6b87fadc4e05638/reference/v7.json#L1175-L1190).

**Comment by tristen** [comment]
:+1:
